backplane:
  redisUri: "redis://<HOSTNAME>:6379"
  redisPassword: "<PASSWORD>"
  queues:
    - name: "fpga"
      allowUnmatched: true
      properties:
        - name: "cw310"
          value: "1"
    - name: "rest"
      allowUnmatched: true
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max_cores"
          value: "*"

